export const C = {
  primary: "#2563EB",
  primaryHover: "#1D4ED8",
  danger: "#DC2626",
  dangerHover: "#B91C1C",
  dark: "#374151",
  darkHover: "#1F2937",
  bg: "#F3F4F6",
  sidebar: "#F9FAFB",
  border: "#E5E7EB",
  headerBg: "#E5E7EB",
  white: "#FFFFFF",
  text: "#111827",
  textMuted: "#6B7280",
  tableHead: "#F3F4F6",
};

export const S = {
  page: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    background: C.bg,
    color: C.text,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: C.headerBg,
    borderBottom: `1px solid ${C.border}`,
    padding: "0 24px",
    height: 48,
    flexShrink: 0,
  },
  headerTitle: { fontWeight: 700, fontSize: 15 },
  headerUser: { fontSize: 13, color: C.textMuted },
  headerUserLink: { color: C.primary, textDecoration: "none", fontWeight: 500 },
  body: { display: "flex", flex: 1 },
  sidebar: {
    width: 200,
    background: C.sidebar,
    borderRight: `1px solid ${C.border}`,
    padding: "16px 0",
    flexShrink: 0,
  },
  navItem: (active) => ({
    display: "block",
    padding: "8px 20px",
    fontSize: 14,
    cursor: "pointer",
    color: active ? C.primary : C.text,
    fontWeight: active ? 600 : 400,
    background: active ? "#EFF6FF" : "transparent",
    borderLeft: active ? `3px solid ${C.primary}` : "3px solid transparent",
    transition: "all .15s",
    userSelect: "none",
  }),
  main: { flex: 1, padding: "28px 32px", overflowY: "auto" },
  pageTitle: { fontSize: 22, fontWeight: 700, marginBottom: 20 },
  card: {
    background: C.white,
    border: `1px solid ${C.border}`,
    borderRadius: 8,
    padding: 20,
    marginBottom: 20,
  },
  btn: (variant = "primary", size = "md") => {
    const colors = {
      primary: { bg: C.primary, hover: C.primaryHover, text: "#fff" },
      danger: { bg: C.danger, hover: C.dangerHover, text: "#fff" },
      secondary: { bg: C.dark, hover: C.darkHover, text: "#fff" },
      outline: { bg: "#fff", hover: "#F3F4F6", text: C.text, border: C.border },
    };
    const c = colors[variant];
    const pad = size === "sm" ? "4px 12px" : "8px 20px";
    const fs = size === "sm" ? 13 : 14;
    return {
      padding: pad,
      fontSize: fs,
      fontWeight: 600,
      background: c.bg,
      color: c.text,
      border: c.border ? `1px solid ${c.border}` : "none",
      borderRadius: 6,
      cursor: "pointer",
      transition: "background .15s",
    };
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    fontSize: 14,
    border: `1px solid ${C.border}`,
    borderRadius: 6,
    outline: "none",
    boxSizing: "border-box",
    background: C.white,
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    fontSize: 14,
    border: `1px solid ${C.border}`,
    borderRadius: 6,
    outline: "none",
    background: C.white,
    cursor: "pointer",
    appearance: "auto",
  },
  label: { display: "block", fontSize: 14, fontWeight: 600, marginBottom: 6 },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 14 },
  th: {
    background: C.tableHead,
    padding: "10px 14px",
    textAlign: "left",
    fontWeight: 600,
    borderBottom: `1px solid ${C.border}`,
    borderTop: `1px solid ${C.border}`,
  },
  td: {
    padding: "10px 14px",
    borderBottom: `1px solid ${C.border}`,
    verticalAlign: "middle",
  },
  statCard: {
    background: C.white,
    border: `1px solid ${C.border}`,
    borderRadius: 8,
    padding: "20px 24px",
    textAlign: "center",
    flex: 1,
  },
  statLabel: { fontSize: 13, color: C.textMuted, marginBottom: 8 },
  statValue: { fontSize: 28, fontWeight: 700 },
  qlCard: {
    background: C.white,
    border: `1px solid ${C.border}`,
    borderRadius: 8,
    padding: "16px 20px",
    display: "flex",
    alignItems: "center",
    gap: 14,
    cursor: "pointer",
    transition: "box-shadow .15s",
    flex: 1,
    minWidth: 0,
  },
  qlIcon: { fontSize: 28, flexShrink: 0 },
  qlTitle: { fontSize: 14, fontWeight: 600, marginBottom: 2 },
  qlDesc: { fontSize: 12, color: C.textMuted },
  row: (gap = 12) => ({ display: "flex", gap, alignItems: "center" }),
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  sectionTitle: { fontSize: 16, fontWeight: 700, marginBottom: 14 },
};
